,target,doc
0,1,VMware: vmware_object_role_permission fails when principal is used
1,1,<!--- Verify first that your issue is not already reported on GitHub -->
2,1,<!--- Also test if the latest release and devel branch are affected too -->
3,1,"<!--- Complete *all* sections as described, this form is processed automatically -->"
4,,
5,1,##### SUMMARY
6,1,"When using option principal instead of group, this code fails."
7,,
8,1,##### ISSUE TYPE
9,1,- Bug Report
10,,
11,1,##### COMPONENT NAME
12,1,vmware_object_role_permission
13,,
14,1,##### ANSIBLE VERSION
15,1,"<!--- Paste verbatim output from ""ansible --version"" between quotes -->"
16,0,```
17,0,Ansible 2.7.7 (Module was imported using import folder in AWX)
18,0,```
19,,
20,1,##### CONFIGURATION
21,1,"<!--- Paste verbatim output from ""ansible-config dump --only-changed"" between quotes -->"
22,0,```
23,0,Standard Ansible AWX AWX 3.0.1.0
24,0,```
25,,
26,1,##### OS / ENVIRONMENT
27,1,CENTOS 7.
28,,
29,1,##### STEPS TO REPRODUCE
30,1,"1) Install AWX, import a playbook with inventory/vmware_object_role_permission.py in it"
31,1,2) Run vmware_object_role_permission module with principal user.
32,,
33,,
34,1,<!--- Paste example playbooks or commands between quotes below -->
35,0,```
36,0,    -
37,0,      name: Assign a user to VM folder
38,0,      vmware_object_role_permission:
39,0,        hostname: '{{ vcenter_hostname }}'
40,0,        username: '{{ vcenter_username }}'
41,0,        password: '{{ vcenter_password }}'
42,0,        principal: 'ad\{{ item }}'
43,0,"        object_name: ""{{ name }}"""
44,0,        state: present
45,0,"        role: ""Role"""
46,0,        validate_certs: no
47,0,      delegate_to: localhost
48,,
49,0,```
50,,
51,1,<!--- HINT: You can paste gist.github.com links for larger files -->
52,,
53,1,##### EXPECTED RESULTS
54,1,<!--- Describe what you expected to happen when running the steps above -->
55,1,Assign a user to a role for a specified folder
56,,
57,1,##### ACTUAL RESULTS
58,1,<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
59,0,```
60,0,{
61,0,"    ""_ansible_parsed"": false,"
62,0,"    ""exception"": ""Traceback (most recent call last):\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 113, in <module>\n    _ansiballz_main()\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 239, in <module>\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 234, in main\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 128, in __init__\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 170, in setup_permission\nAttributeError: 'VMwareObjectRolePermission' object has no attribute 'is_group'\n"","
63,0,"    ""_ansible_no_log"": false,"
64,0,"    ""_ansible_delegated_vars"": {"
65,0,"        ""ansible_delegated_host"": ""localhost"","
66,0,"        ""ansible_host"": ""localhost"""
67,0,"    },"
68,0,"    ""module_stderr"": ""Traceback (most recent call last):\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 113, in <module>\n    _ansiballz_main()\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \""/root/.ansible/tmp/ansible-tmp-1551427371.24-104946698235266/AnsiballZ_vmware_object_role_permission.py\"", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 239, in <module>\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 234, in main\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 128, in __init__\n  File \""/tmp/ansible_vmware_object_role_permission_payload_pXNiDq/__main__.py\"", line 170, in setup_permission\nAttributeError: 'VMwareObjectRolePermission' object has no attribute 'is_group'\n"","
69,0,"    ""changed"": false,"
70,0,"    ""module_stdout"": """","
71,0,"    ""rc"": 1,"
72,0,"    ""msg"": ""MODULE FAILURE\nSee stdout/stderr for the exact error"""
73,0,}
74,0,```
75,,
76,1,"Seems like initializing self.is_group = False, like so:"
77,0,```
78,0,"        if self.params.get('principal', None) is not None:"
79,0,            self.applied_to = self.params['principal']
80,0,            self.is_group = False
81,0,"        elif self.params.get('group', None) is not None:"
82,0,            self.applied_to = self.params['group']
83,0,            self.is_group = True
84,0,```
85,1,should solve the problem
